### ISSUE TITLE
doesnt appear to be working within the files in an ext/style/ 

### ISSUE THREAD

**Issue by neuropass** [phpbbmodders/phpbb-3.1-ext-groupswitch#1]
looks like its not working within the files in an ext/style/ folder.

Would that be possible?

**Comment by bonelifer** [comment]
@RMcGirr83 any ideas?

**Comment by rmcgirr83** [comment]
Not without more information and I have pretty given up on this one in favor of this one https://github.com/marttiphpbb/phpbb-ext-grouptempvars

**Comment by bonelifer** [comment]
@neuropass as per above: Try this extension instead: https://github.com/marttiphpbb/phpbb-ext-grouptempvars
